gpus=all
hwaccel
multi-monitor=largest
rotate=left

font-engine=freetype
font-size=16
font-name=DepartureMono Nerd Font

#xkb-model=pc102
xkb-layout=us
#xkb-variant=
xkb-options=caps:swapescape,ctrl:swap_ralt_rctl
xkb-repeat-delay=160
xkb-repeat-rate=50

## Enable mouse
#mouse
## Force software cursor
#soft-cursor

dpms-timeout=600

term=xterm-256color
