kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
if_iwlwifi_load="YES"
iwlwifi_firmware_load="YES"
autoboot_delay="0"
beastie_disable="YES"
boot_mute="YES"
hw.usb.no_boot_wait=1
cpuctl_load="YES"
acpi_call_load="YES"
acpi_ibm_load="YES"
kern.boottrace.enabled="1"
screen.font="12x24"
cpu_microcode_load="YES"
cpu_microcode_name="/boot/firmware/intel-ucode.bin"
