# General Settings
set -g escape-time 0
set -g status-keys vi
set -g mode-keys vi
set -g focus-events on
set -g default-terminal "screen-256color"
set -gq allow-passthrough on
set -g monitor-activity on
set -g visual-activity off

# status line
set -g status-left-length 99
set -g status-right-length 99
set -g status-right "#[fg=yellow,bold]CPU: #[reverse] #(cpu-usage)%% #[noreverse] MEM: #[reverse] #(mem-usage)%% #[noreverse] BAT: #[reverse] #(bat-level)%% #[noreverse] #[reverse]%H:%M:%S"
set -g status-left ""
set -g window-status-current-style "fg=yellow bg=default bold"
set -g window-status-current-format " #S "
set -g status-position top
set -g status-justify absolute-centre
set -g status-style bg=default
set -g status-interval 1

# dim inactive windows
set-option -g window-style        "fg=colour239,bg=default"
set-option -g window-active-style "fg=white,bg=default"

# invisible borders
set -g pane-border-style          "fg=black,bg=default"
set -g pane-active-border-style   "fg=black,bg=default"

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

run 'sh -c "[ -e $XDG_CONFIG_HOME/tmux/plugins/tpm/tpm ] || git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm"'
run 'sh -c "$XDG_CONFIG_HOME/tmux/plugins/tpm/bin/install_plugins"'
run 'sh -c "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"'
