set number
set rnu
set copyindent
set smartcase
set shiftwidth=4
set tabstop=4
set autocomplete
set cmdheight=1
" treat hyphens as part of a word
set iskeyword+=-
" glob searching in dirs
set path+=**
set autoread
set wildmode=list,longest,noinsert
set wildignore+=*.o,*.obj,*.pyc,*.so,*.dll,*.git/
set scrolloff=6
set sidescrolloff=8
set diffopt+=linematch:60
" let undodir = expand('~/.vim/undodir')
set cursorline
set showmatch
set matchtime=1
set breakindent
set list
set listchars=tab:\\u2502\ ,trail:·,extends:→,precedes:←,trail:$
set linebreak
set wrap
set showbreak=↪\\
set signcolumn=yes
set laststatus=1
set splitright
set foldmethod=indent
set foldenable
set foldlevelstart=9
set foldopen-=search
syntax on
set conceallevel=2
set concealcursor=nc
set lazyredraw
set synmaxcol=300
set softtabstop=4
set autoindent
set smartindent
set shiftround
set incsearch
set hlsearch
set timeoutlen=500
set ttimeoutlen=0
set whichwrap=
set wildignorecase
set completeopt=menu,fuzzy,popup,longest
set completepopup=
set shortmess+=co
let g:netrw_banner = 0
let g:netrw_liststyle = 3
set updatetime=100
set redrawtime=10000
set maxmempattern=20000
set visualbell
set virtualedit=block
set cpoptions+=$
set spelllang=en_gb

filetype plugin indent on

" Black DarkGrey LightGrey White

let PureBlack = 16

hi SpecialKey      ctermfg=DarkYellow
hi NonText         ctermfg=DarkGrey
hi Directory       ctermfg=DarkCyan
hi ErrorMsg        ctermfg=White ctermbg=DarkRed
hi IncSearch       cterm=reverse ctermfg=Black ctermbg=Yellow
hi Search          ctermfg=Black ctermbg=DarkYellow
hi MoreMsg         ctermfg=DarkGreen
hi ModeMsg         cterm=bold
hi LineNr          ctermfg=LightGrey ctermbg=NONE
hi LineNrAbove    ctermfg=NONE ctermbg=NONE cterm=NONE
hi LineNrBelow    ctermfg=NONE ctermbg=NONE cterm=NONE
hi CursorLineNr    cterm=bold ctermfg=LightGrey ctermbg=NONE
hi Question        ctermfg=DarkGreen
hi StatusLine      ctermbg=Black
hi StatusLineNC    cterm=reverse ctermfg=DarkGrey
hi VertSplit       cterm=reverse ctermfg=Black
hi Title           cterm=bold ctermfg=DarkBlue
hi Visual         ctermfg=Black ctermbg=Yellow
hi VisualNOS       cterm=bold,underline
hi WarningMsg      ctermfg=DarkRed
hi WildMenu        ctermfg=Black ctermbg=DarkBlue
hi Folded          ctermfg=LightGrey ctermbg=Black
hi FoldColumn      ctermfg=DarkBlue ctermbg=Black
hi DiffAdd         ctermfg=Green ctermbg=NONE
hi DiffChange      ctermfg=Yellow ctermbg=NONE
hi DiffDelete      ctermfg=Red ctermbg=NONE
hi DiffText        cterm=bold ctermfg=248
hi SignColumn      ctermfg=DarkBlue ctermbg=NONE
hi Conceal        ctermfg=LightGrey ctermbg=242
hi SpellBad        ctermbg=224
hi SpellCap        ctermbg=DarkYellow
hi SpellRare       ctermbg=225
hi SpellLocal      ctermbg=Cyan
hi Pmenu          ctermfg=White ctermbg=Black
hi PmenuSel       ctermfg=White ctermbg=Blue
hi PmenuSbar      ctermbg=Black
hi PmenuThumb     ctermbg=DarkGrey
hi PmenuShadow    ctermfg=DarkGrey ctermbg=Black
hi TabLine         cterm=underline ctermfg=Black ctermbg=LightGrey
hi TabLineSel      cterm=bold
hi TabLineFill     cterm=reverse
hi CursorColumn    ctermbg=Black
hi CursorLine      ctermbg=234 cterm=NONE
hi ColorColumn     ctermbg=234
hi StatusLineTerm  cterm=bold ctermfg=White ctermbg=DarkGreen
hi StatusLineTermNC  ctermfg=White ctermbg=DarkGreen
hi MsgArea        ctermfg=LightGrey ctermbg=NONE cterm=NONE
hi ComplMatchIns  ctermfg=LightBlue ctermbg=NONE cterm=NONE
hi Added          ctermfg=DarkGreen
hi Normal         ctermfg=NONE ctermbg=NONE cterm=NONE
hi MatchParen      cterm=bold ctermfg=White ctermbg=Blue
hi ToolbarLine     ctermbg=NONE
hi ToolbarButton  cterm=bold ctermfg=White ctermbg=242
hi Comment         ctermfg=LightGrey ctermbg=NONE
hi Constant        ctermfg=DarkYellow
hi Special         ctermfg=DarkCyan
hi Identifier      ctermfg=DarkRed
hi Statement       ctermfg=DarkMagenta
hi PreProc         ctermfg=DarkMagenta
hi Type            ctermfg=DarkYellow
hi Underlined      cterm=underline ctermfg=DarkMagenta
hi Ignore         ctermfg=White
hi Changed        ctermfg=Blue
hi Removed        ctermfg=Red
hi Error           cterm=bold ctermfg=White ctermbg=Red
hi Todo            cterm=reverse ctermfg=Yellow ctermbg=NONE
hi Bold            cterm=bold
hi Italic          cterm=italic
hi BoldItalic      cterm=bold,italic
hi String         ctermfg=DarkGreen ctermbg=NONE
hi Function       ctermfg=DarkBlue ctermbg=NONE
hi PmenuBorder       ctermfg=234 ctermbg=234

" KEYBINDS

let mapleader = " "

" Set marks using leader + shift + number
nnoremap <leader>! mA
nnoremap <leader>" mB
nnoremap <leader>£ mC
nnoremap <leader>$ mD
nnoremap <leader>% mE
nnoremap <leader>^ mF
nnoremap <leader>& mG
nnoremap <leader>* mH
nnoremap <leader>) mI
nnoremap <leader>_ mJ

" Jump to marks
nnoremap <leader>1 'A`"zz
nnoremap <leader>2 'B`"zz
nnoremap <leader>3 'C`"zz
nnoremap <leader>4 'D`"zz
nnoremap <leader>5 'E`"zz
nnoremap <leader>6 'F`"zz
nnoremap <leader>7 'G`"zz
nnoremap <leader>8 'H`"zz
nnoremap <leader>9 'I`"zz
nnoremap <leader>0 'J`"zz

" Move visual blocks
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Keep cursor in place when joining lines
nnoremap J mzJ`z

" Keep cursor centered during scrolling and searching
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzz
nnoremap N Nzz

" Paste over selection without losing current register
xnoremap <leader>p "_dP

" Delete to void register (black hole)
nnoremap <leader>d "_d
vnoremap <leader>d "_d

nnoremap <leader>i :echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')<CR>

nnoremap <Esc> :nohlsearch <CR>

nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <c-k> <c-w>k
nnoremap <C-j> <C-w>j

nnoremap j gj
nnoremap k gk

" Stay in visual mode after indenting
vnoremap < <gv
vnoremap > >gv

" Supertab
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<Tab>"
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
inoremap <expr> <Esc> pumvisible() ? "\<C-e><Esc>" : "\<Esc>"

" Plugins
set runtimepath^=$XDG_DATA_HOME/vim

let data_dir = empty($XDG_DATA_HOME) ? '~/.local/share/vim' : $XDG_DATA_HOME . '/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin()

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
Plug 'junegunn/fzf.vim'
Plug 'vimpostor/vim-tpipeline'

if has('nvim') || has('patch-8.0.902')
	Plug 'mhinz/vim-signify'
else
	Plug 'mhinz/vim-signify', { 'tag': 'legacy' }
endif

if has('nvim') || has('patch-8.2.000')
	Plug 'dense-analysis/ale'
endif

call plug#end()

let g:signify_sign_add = '+'
let g:signify_sign_delete = '-'
let g:signify_sign_change = '~'

nnoremap <leader>f :Files<CR>

let g:fzf_vim = {}
let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 1.0 } }
let g:fzf_colors = { 'border': [ 'fg', 'PmenuBorder', 'bg', 'PmenuBorder' ] }

