clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="t480s"
keymap="my.kbd"
wlans_iwlwifi0="wlan0"
ifconfig_wlan0="WPA  DHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"
create_args_wlan0="country GB regdomain ETSI"
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
local_unbound_enable="YES"
powerd_enable="NO"
moused_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"

kld_list="i915kms"
allscreens_flags="-r 100 17"
